/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/Sample copy.vue')['default']
    DataPaginated: typeof import('./src/components/DataPaginated.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ImageDiff: typeof import('./src/components/ImageDiff.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sample: typeof import('./src/components/Sample.vue')['default']
    SampleInfo: typeof import('./src/components/SampleInfo.vue')['default']
    SampleSize: typeof import('./src/components/SampleSize.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TestStatus: typeof import('./src/components/TestStatus.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
