/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DataPaginated: typeof import('./src/components/DataPaginated.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ImageDiff: typeof import('./src/components/ImageDiff.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
